#Manage Puppet Module dependencies with librarian-puppet

forge 'http://forge.puppetlabs.com'

mod 'rj-zabbix',
	:git => "https://github.com/eduardodicarte/rj-zabbix.git"

mod 'rj-firewall',
	:git => "https://github.com/eduardodicarte/rj-firewall.git"
